services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "YourStrong!Passw0rd"
      ACCEPT_EULA: "Y"
    networks:
      - mynetwork

  php-apache:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php-apache-1
    ports:
      - "8080:80"
    volumes:
      - ./html:/var/www/html
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
